#配置数据源
spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://rm-bp13kp03njpe33xdy.mysql.rds.aliyuncs.com:3306/qshop_bbc?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: qshop_bbc
      password: qshop_bbc123

      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat

      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  #配置 Jpa
  jpa:
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: none
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password: Bs123456
    #连接超时时间
    timeout: 5000

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认2小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 7200000
  # 在线用户key
  online-key: platform-online-token
  # 验证码
  code-key: platform-code-key

#是否允许生成代码，生产环境设置为false
generator:
  enabled: false

#如果生产环境要开启swagger，需要配置请求地址
#springfox:
#  documentation:
#    swagger:
#      v2:
#        host: # 接口域名或外网ip

#是否开启 swagger-ui
swagger:
  enabled: true
  title: qshop商城平台管理后台API
  serverUrl: http://localhost:8001
  version: 2.0

# 文件存储路径
file:
  path: /home/qshop/file/platform/
  avatar: /home/qshop/avatar/platform/
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5
  localUrl:

aliyun:
  endpoint: oss-cn-shanghai.aliyuncs.com
  accessKeyId: mwKYuOkSIPZFnyHH
  accessKeySecret: wRZ3V2dhol8nfLpSj1tWx9v5ZbqFlq
  bucketName: test-lqmall-image
  path: b2c/qshop/material/
  url: https://imagelqmall.iyyou.com/